#!/usr/bin/ksh -x

#===========================================================================
#
# wavefront SMF method
# --------------------
#
# A simple script to start the Wavefront proxy on a SunOS system.
# SMF can stop it without assistance. You might need to change the
# heap size
#
#===========================================================================

PATH=/bin:/opt/local/bin

WF_BASEDIR=__PREFIX__/$(ls __PREFIX__ | grep proxy | tail -1)
WF_REPO=${WF_BASEDIR}/repo
WF_CONFIG_FILE=/config/wavefront/wavefront.conf

java -Xmx500m -Xms200m -server -verbosegc \
    -XX:-UseParallelOldGC -XX:OnOutOfMemoryError="kill -9 %p" \
    -Djava.util.logging.SimpleFormatter.format="%1$tY-%1$tm-%1$td%1$tH:%1$tM:%1$tS %4$-6s %2$s %5$s%6$s%n" \
    -classpath "$(find $WF_REPO -name \*jar | sort -r | tr \\n :)" \
    -Dapp.name="agent" \
    -Dapp.pid="$$" \
    -Dapp.repo="$WF_REPO" \
    -Dapp.home="$WF_BASEDIR" \
    -Dbasedir="$WF_BASEDIR" \
    com.wavefront.agent.PushAgent \
    -f $WF_CONFIG_FILE \
>>/var/log/wavefront/wavefront-proxy.log 2>&1 &

PID=$!
checks=20
print "Process launched as ${PID}. Waiting for connection."

while (( checks > 0 ))
do
    sleep 1

    if ! ps -p $PID >/dev/null 2>&1
    then
        print -u2 "FAILED: process is dead "
        exit 1
    fi

    if print < /dev/tcp/localhost/2878 >/dev/null 2>&1
    then
        print " OK"
        exit 0
    fi

    print -n .
	(( checks = checks - 1 ))
done

ps -p $PID >/dev/null 2>&1 && kill $PID || kill -9 $PID
print -u2 " FAILED. Cannot access port 3878"
exit 1
