#!/usr/bin/ksh

#===========================================================================
#
# wavefront SMF method
# --------------------
#
# A simple script to start the Wavefront proxy on a SunOS system.
# SMF can stop it without assistance. You might need to change the
# heap size
#
#===========================================================================

propval() {
	svcprop -p options/$1 wavefront/proxy
}

WF_BASEDIR=__PREFIX__/$(ls __PREFIX__| grep proxy | tail -1)
WF_REPO=${WF_BASEDIR}/repo
PATH=/bin:/opt/local/java/bin

java -Xmx$(propval heap_max) -Xms$(propval heap_min) -server -verbosegc \
     -classpath "$(find $WF_REPO -name \*jar | sort -r | tr \\n :)" \
	 -Dlog4j.configurationFile=/config/wavefront/log4j2.xml \
     -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
     -Dapp.home="$WF_BASEDIR" \
     -Dbasedir="$WF_BASEDIR" \
     com.wavefront.agent.PushAgent \
	 -f $(propval config_file) &

PID=$!
checks=20
print "Process launched as ${PID}. Waiting for connection."

while (( checks > 0 ))
do
    sleep 1

    if ! ps -p $PID >/dev/null 2>&1
    then
        print -u2 "FAILED: process is dead "
        exit 1
    fi

    if print < /dev/tcp/localhost/2878 >/dev/null 2>&1
    then
        print " OK"
        exit 0
    fi

    print -n .
        (( checks = checks - 1 ))
done

ps -p $PID >/dev/null 2>&1 && kill $PID || kill -9 $PID
print -u2 " FAILED. Cannot access port 3878"
exit 1
